### ISSUE TITLE
はなみTLでミュート関連の機能が機能していない

### ISSUE THREAD

**Issue by tkmrgit** [HanaMisskey/misskey#50]
### 💡 Summary

はなみTLを観ているが、ユーザーミュートやサーバーミュート等のミュート関連機能がはなみTLでは機能していないように見える

### 🥰 Expected Behavior

ミュート関連機能ははなみTLでも有効

### 🤬 Actual Behavior

ミュート関連機能ははなみTLでは機能していない

### 💻 Frontend Environment

```markdown
misskey.flowers
2024.8.0-hanami.85e8eea40
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kanarikanaru** [comment]
ありがとうございます。
人気の投稿部分においてインスタンスミュートが機能していない事象を確認しました。
修正予定です。
